---
base:
  debug_mode: release
  time_location: Asia/Shanghai
log:
  #日志打印最低级别
  log_level: error
  #文件写入配置
  file_writer:
    on: false
    log_path: ./logs/common.inf.log
    rotate_log_path: ./logs/common.inf.log
    wf_log_path: ./logs/common.wf.log
    rotate_wf_log_path: ./logs/common.wf.log
  #工作台输出
  console_writer:
    on: true
    color: true